package main

import (
	"aiPr/chp18"
	"fmt"
)

func main() {
	fmt.Println("entry!")
	//chp2.RunChp2FN1()
	//chp2.RunChp2FN2()
	//chp2.RunChp2FN3()
	//chp2.RunChp22FN1()
	//chp2.RunChp22FNSingleDot()
	//chp2.RunChp22FNMultiDot()
	//chp2.RunChp23FNTrans()
	//chp2.RunChp23FNBatch()
	//ml.RunChp3InnerLayer()
	//ml.RunChp32TrainDraw()
	//ml.RunChp32TrainDensLayer()
	//ml.RunReLUfunc1()
	//	ml.RunReLUfuncDense()
	//ml.RunSoftmax1()
	//ml.RunSoftmax2()
	//ml.RunSoftmax3()
	//ml.RunLossFunc1()
	//	ml.RunLossFunc2()
	//ml.RunLossFunc3()
	//ml.RunLossFunc4()
	//ml.RunLossFunc5()
	//chp6.RunOptFunc1()
	//chp6.RunOptFunc2()
	//chp6.RunOptFunc3()
	//chp7.RunImpFunc1()
	//chp9.RunBackpropagationFunc1()
	//chp9.RunBackpropagationMultiFunc2()
	//chp9.RunBackpropagationMultiFunc3()
	//chp9.RunBackpropagationBiasFunc4()
	//chp9.RunBackpropagationReLUFunc5()
	//	chp9.RunBackpropagationAllFunc6()
	//chp9.RunBackpropagationCalcFunc7()
	//chp9.RunBackpropagationLossFunc8()
	//chp9.RunBackpropagationLossFunc9()
	//chp9.RunFullTestwithLossFunc10()
	//ml.RunUpstreamTestFunc10()
	//ml.RunDecayFunc11()
	//ml.RunUpstreamTestwithDecayFunc12()
	//ml.RunUpstreamTestwithAdagradFunc13()
	//ml.RunUpstreamTestwithRMSpropFunc14()
	//ml.RunUpstreamTestwithAdamFunc15()
	//ml.RunUpstreamTestwithNewDataFunc16()
	//chp14.RunRegulizerFunc1()
	//chp14.RunRegulizerIncreaseNodesFunc1()
	//chp15.RunDropoutFunc1()
	//chp16.RunRegressionFunc1()
	//chp16.RunRegressionFunc2()
	//chp17.RunLinearActFunc2()
	//chp17.RunLinearActFunc3()
	chp18.RunModelTestFunc1()

	return

}
