package main

import (
	"aiPr/chp14"
	"fmt"
)

func main() {
	fmt.Println("entry!")
	//chp2.RunChp2FN1()
	//chp2.RunChp2FN2()
	//chp2.RunChp2FN3()
	//chp2.RunChp22FN1()
	//chp2.RunChp22FNSingleDot()
	//chp2.RunChp22FNMultiDot()
	//chp2.RunChp23FNTrans()
	//chp2.RunChp23FNBatch()
	//chp3.RunChp3InnerLayer()
	//chp3.RunChp32TrainDraw()
	//chp3.RunChp32TrainDensLayer()
	//chp4.RunReLUfunc1()
	//	chp4.RunReLUfuncDense()
	//chp4.RunSoftmax1()
	//chp4.RunSoftmax2()
	//chp4.RunSoftmax3()
	//chp5.RunLossFunc1()
	//	chp5.RunLossFunc2()
	//chp5.RunLossFunc3()
	//chp5.RunLossFunc4()
	//chp5.RunLossFunc5()
	//chp6.RunOptFunc1()
	//chp6.RunOptFunc2()
	//chp6.RunOptFunc3()
	//chp7.RunImpFunc1()
	//chp9.RunBackpropagationFunc1()
	//chp9.RunBackpropagationMultiFunc2()
	//chp9.RunBackpropagationMultiFunc3()
	//chp9.RunBackpropagationBiasFunc4()
	//chp9.RunBackpropagationReLUFunc5()
	//	chp9.RunBackpropagationAllFunc6()
	//chp9.RunBackpropagationCalcFunc7()
	//chp9.RunBackpropagationLossFunc8()
	//chp9.RunBackpropagationLossFunc9()
	//chp9.RunFullTestwithLossFunc10()
	//chp10.RunUpstreamTestFunc10()
	//chp10.RunDecayFunc11()
	//chp10.RunUpstreamTestwithDecayFunc12()
	//chp10.RunUpstreamTestwithAdagradFunc13()
	//chp10.RunUpstreamTestwithRMSpropFunc14()
	//chp10.RunUpstreamTestwithAdamFunc15()
	//chp10.RunUpstreamTestwithNewDataFunc16()
	chp14.RunRegulizerFunc1()
	return

}
